---
 simulation:
  seed: 103 # Random seed
 map:
  x: 100 # Size of map
  y: 100
  tribes: 50 # Number of start tribes
  terrains:
    #All terains used to generate map in order.
    - name: 'Plains'
      color: [255, 255, 0]
      production_multiplier: 3.5 
    - name: 'Woods'
      color: [0, 255, 0]
      production_multiplier: 4.8
      perlin_octave: 20
      perlin_threshold: 0.05
    - name: 'Silver'
      production_multiplier: 5.5
      color: [255, 255, 153]
      perlin_octave: 20
      perlin_threshold: 0.35
    - name: 'River'
      color: [0, 0, 255]
      crossable: False
      perlin_octave: 10 
      perlin_threshold: 0.1
 tribes:
  default_tribe: #it's used to describe default tribe
     
  start_tribes:
    - name: 'Lechici'
      combat_ability: 1.5
      growth_rate: 0.5 
      type: 'Nomad'
      points_to_evolve: 20