---
 simulation:
  seed: 102
 map:
  x: 100
  y: 100
  tribes: 50
  terrains:
    - name: 'Plains'
      color: [255, 255, 0]
      production_multiplier: 1.3
    - name: 'Woods'
      color: [0, 255, 0]
      production_multiplier: 1.8
      perlin_octave: 20
      perlin_threshold: 0.05
    - name: 'Silver'
      production_multiplier: 5
      color: [255, 255, 153]
      perlin_octave: 20
      perlin_threshold: 0.35
    - name: 'River'
      color: [0, 0, 255]
      crossable: False
      perlin_octave: 10
      perlin_threshold: 0.05
 tribes:
  start_tribes:
    - name: 'Lechici'
      combat_ability: 1.5
      growth_rate: 0.5 
      type: 'Nomad'
      points_to_evolve: 20