---
 simulation:
  seed: 102 # Random seed
 map:
  x: 200 # Size of map
  y: 200
  tribes: 50 # Number of start tribes
  terrains:
    #All terains used to generate map in order.
    - name: 'Plains'
      color: [255, 255, 0]
      production_multiplier: 1.3 
    - name: 'Woods'
      color: [0, 255, 0]
      production_multiplier: 1.8
      perlin_octave: 20
      perlin_threshold: 0.05
    - name: 'Silver'
      production_multiplier: 5
      color: [255, 255, 153]
      perlin_octave: 20
      perlin_threshold: 0.35
    - name: 'River'
      color: [0, 0, 255]
      crossable: False
      perlin_octave: 10 
      perlin_threshold: 0.05
 tribes:
  start_tribes:
    - name: 'Lechici'
      combat_ability: 1.2
      production_multiplier: 1.0 
      type: 'Nomad'
      points_to_evolve: 20
      color_range: [150,0,0,255,0,0]
      inteligent_directions: True
    - name: 'Czesi'
      combat_ability: 0.8
      production_multiplier: 1.1 
      type: 'Nomad'
      points_to_evolve: 40
      color_range: [0,0,150,0,0,255]
      inteligent_directions: False